plugin: amazon.aws.aws_ec2
aws_profile: default
private_key_file: ~/.ssh/lf-ansible

regions:
  - us-east-2
filters:
  "tag:Controller": "Ansible"
  "tag:Owner": "lf"
groups:
  redhat: "'redhat' in tags.System"
  debian: "'debian' in tags.System"