---
- hosts: rhel
  become: true
  tasks:
  - name: Enable EPEL repository on Red Hat 8 and later
    dnf_repository:
      name: epel
      description: Extra Packages for Enterprise Linux 8 - $basearch
      baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      gpgcheck: yes
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      enabled: yes

  - name: Install Certbot on Red Hat
    become: true
    dnf:
      name: certbot
      state: present

  - name: Update OpenSSH on Red Hat
    become: true
    dnf:
      name: openssh-server
      state: latest

# ansible-playbook install_servers_rhel.yml
