---
- hosts: rhel
  become: true
  tasks:
  - name: Enable EPEL repository on Red Hat 8 and later
    dnf_repository:
      name: epel
      description: Extra Packages for Enterprise Linux 8 - $basearch
      baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      gpgcheck: yes
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      enabled: yes

  - name: Install Certbot on Red Hat
    become: true
    dnf:
      name: certbot
      state: present

  - name: Verify certbot is installed on RedHat or CentOS
    yum:
      name: certbot
      state: present
    register: certbot_installed

  - debug:
      msg: "Certbot is installed"
    when: certbot_installed.changed == False

  - name: Update OpenSSH on Red Hat
    become: true
    dnf:
      name: openssh-server
      state: latest

  - name: Verify OpenSSH version on Red Hat
    shell: rpm -q openssh-server
    register: ssh_version
    changed_when: false

  - debug:
      msg: "OpenSSH version is {{ ssh_version.stdout }}"

# ansible-playbook install_servers_rhel.yml
