#!/usr/bin/env groovy
@Library('lib-aline')
def gv

pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('LF_AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('LF_AWS_SECRET_ACCESS_KEY')
        AWS_ID = credentials('AWS_ID')
        AWS_REGION = credentials('LF_ALINE_AWS_REGION')
        ALINE_TFVARS = credentials('LF_ALINE_TFVARS')
    }
    stages {
        stage('terraform plan') {
            when { not {branch pattern: "^(feature/).*", comparator: "REGEXP"}}
            steps {
                script {
                    ansible.tfplan()
                }
            }
        }
        stage('terraform apply') {
            when { not {branch pattern: "^(feature/).*", comparator: "REGEXP"}}
            steps {
                script {
                    ansible.tfapply()
                }
            }
        }
        stage('ansible install') {
            steps {
                script {
                    ansible.install()
                }
            }
        }
        stage('ansible tests') {
            steps {
                script {
                    ansible.tests()
                }
            }
        }
    }
    Jenkinsfile {
        filename 'path/to/Jenkinsfile'
    }
    post {
        always {
            cleanWs()
        }
    }
}