#!/bin/bash
TFLINT_CONFIG="/Users/lynda/Desktop/repo/aline-repo-files/dev-infra-cc/aws/.tflint.hcl"

find modules environments \
  -type f \
  -name '*.tf' \
  ! -path '*/.terraform/*' \
  -exec dirname {} \; \
  | xargs -I {} sh -c '
      cp "$2" "$1"
      cd "$1"
      tflint
      terraform fmt -check
      rm .tflint.hcl
      echo "====== $1 processed ======"
    ' sh {} "$TFLINT_CONFIG"