---
- name: Certbot debian play
  hosts: debian
  user: admin
  tasks:
    - name: Debian - Update OpenSSH on Debian and Ubuntu
      become: True
      apt:
        name: openssh-client
        state: latest
    - name: Update APT Cache
      become: True
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: Remove apt lock file
      become: True
      file:
        state: absent
        path: "/var/lib/dpkg/lock"
    # VERIFY openssh does not rquire updates DEBIAN
    - name: Debian - Verify OpenSSH does not require an update
      become: True
      apt:
        name: openssh-server
        update_cache: yes
        state: latest
      register: apt_output
      changed_when: False
      check_mode: no
    - name: Debian - Install Snap on Ubuntu
      become: True
      apt:
        name: snapd
        state: present
    - name: Debian - Install Certbot with Snap on Ubuntu
      become: True
      shell: snap install certbot --classic
    - name: Debian - Check Certbot status
      become: True
      systemd:
        name: snap.certbot.renew.service
        state: started
        enabled: yes
      register: certbot_status
    # VERIFY certbot is installed DEBIAN
    - name: Update APT Cache
      become: True
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: Remove apt lock file
      become: True
      file:
        state: absent
        path: "/var/lib/dpkg/lock"
    - name: Debian - Verify certbot is installed
      become: True
      package:
        name: certbot
        state: present
      register: certbot_installed
      check_mode: no
- name: Certbot redhat play
  hosts: redhat
  user: ec2-user
  serial: 1
  tasks:
    - name: Redhat - Ensure dnf-plugins are installed.
      become: True
      yum:
        name: dnf-plugins-core
        state: present
    - name: Redhat - Update package cache
      become: True
      dnf:
        update_cache: yes
    - name: Redhat - Import EPEL PGP key.
      become: True
      rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
        state: present
    - name: Redhat - Install EPEL repo.
      become: True
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
    - name: Redhat - Enable EPEL
      become: True
      dnf:
        name: epel-release
        state: present
        enablerepo: extras
    - name: Redhat - Install snapd
      become: True
      dnf:
        name: snapd
        state: present
        enablerepo: epel
    - name: Redhat - Ensure snapd is installed.
      become: True
      package:
        name: snapd
        state: present
      register: snapd_install
    - name: Redhat - Enable snapd
      become: True
      systemd:
        name: snapd.socket
        enabled: True
        state: started
    - name: Redhat - Enable classic snap support.
      become: True
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      when: ansible_os_family != "Debian"
    - name: Redhat - Update snap after install.
      become: True
      shell: snap install core; snap refresh core
      changed_when: True
      failed_when: false
      when: snapd_install is changed
    - name: Redhat - Install certbot via snap.
      become: True
      shell: snap install certbot --classic
    - name: Redhat - Symlink certbot into place.
      become: True
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
      ignore_errors: "{{ ansible_check_mode }}"
    - name: Redhat - Set Certbot script variable.
      become: True
      set_fact:
        certbot_script: /usr/bin/certbot
    # VERIFY Certbot is installed REDHAT
    - name: Redhat - verify Certbot is installed
      become: True
      yum:
        list: certbot
      register: certbot_installed
      changed_when: false
      check_mode: no
    - name: Redhat - Update OpenSSH on RedHat
      become: True
      dnf:
        name: openssh-server
        state: latest
    # VERIFY OpenSSH does not require udpates REDHAT
    - name: Red Hat - Verify OpenSSH does not require an update
      become: true
      yum:
        name: openssh-server
        state: latest
      register: yum_output
      changed_when: false
      check_mode: no

- hosts: all
  become: true
  tasks:
  - name: certbot version
    shell: certbot --version
    register: certbot_version
    when: ansible_facts["distribution"] != "Debian"
  - name: print certbot version
    debug: msg="{{ certbot_version.stderr if (ansible_facts["distribution"] == "Amazon") else certbot_version.stdout }}"
    when: ansible_facts["distribution"] != "Debian"
  - name: openssh version
    shell: ssh -V
    register: openssh_version
  - name: print openssh version
    debug: msg="{{ openssh_version.stderr }}"


# cd ansible
# ansible-playbook -i inventory certbot-lf.yml


