version: "3.8"

x-aws-vpc: ${APP_VPC}
x-aws-loadbalancer: ${APP_LB}

x-variables: &variables
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  APP_SERVICE_HOST: ${LOAD_BALANCER}

x-react-variables: &react-variables
  REACT_APP_MEMBER_DASHBOARD_URL: ${LOAD_BALANCER}
  REACT_APP_API_BASEURL: ${LOAD_BALANCER}
  REACT_APP_API: ${LOAD_BALANCER}/api/

services:
  gateway:
    image: ${REGISTRY}/lf-aline-gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      APP_PORT: ${GATEWAY_PORT}
      PORTAL_LANDING: ${LOAD_BALANCER}
      PORTAL_DASHBOARD: ${LOAD_BALANCER}
      PORTAL_ADMIN: ${LOAD_BALANCER}
      APP_SERVICE_HOST: ${LOAD_BALANCER}
    restart: on-failure

  user:
    image: ${REGISTRY}/lf-aline-user-microservice
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      <<: *variables
      APP_PORT: ${USER_PORT}
    restart: on-failure

  account:
    image: ${REGISTRY}/lf-aline-account-microservice:latest
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    environment:
      <<: *variables
      APP_PORT: ${ACCOUNT_PORT}
    restart: on-failure

  bank:
    image: ${REGISTRY}/lf-aline-bank-microservice:latest
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    environment:
      <<: *variables
      APP_PORT: ${BANK_PORT}
    restart: on-failure

  card:
    image: ${REGISTRY}/lf-aline-card-microservice:latest
    ports:
      - ${CARD_PORT}:${CARD_PORT}
    environment:
      <<: *variables
      APP_PORT: ${CARD_PORT}
    restart: on-failure

  transaction:
    image: ${REGISTRY}/lf-aline-transaction-microservice:latest
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    environment:
      <<: *variables
      APP_PORT: ${TRANSACTION_PORT}
    restart: on-failure

  underwriter:
    image: ${REGISTRY}/lf-aline-underwriter-microservice:latest
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    environment:
      <<: *variables
      APP_PORT: ${UNDERWRITER_PORT}
    restart: on-failure

x-aws-cloudformation:
  Resources:
    GatewayTCP80TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    UserTCP8070TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    AccountTCP8072TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    BankTCP8083TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    CardTCP8084TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    TransactionTCP8073TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    UnderwriterTCP8071TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
